# Common parameters are described in runs/unet/data_v1_4/config/config.yaml

# environment/computational parameters
seed: 42
device: 'cpu'
num_workers: 1
use_deterministic_algorithms: true
warn_only: True

# debugging and logging
verbose: True
log_weight_histograms: False
path_experiment: './runs/unet/sample'
path_wandb: './runs/unet/sample'
path_checkpoints: './runs/unet/sample/checkpoints'
path_sweep: './runs/unet/sample/sweep'
path_sweep_cfg: './runs/unet/sample/config/sweep.yaml'
path_predictions: './runs/unet/sample/predictions'
path_predictions_unet: './runs/unet/sample/predictions'
path_deploy: '/runs/unet/sample/deploy/'
path_eval: './runs/unet/sample/eval_during_training'
model_key: 'unet'
data_key: 'sample'

# wandb logging
wandb_entity: 'blutjens'
wandb_project_name: 'hrmelt-unet-sample'
add_wandb_id_to_ckpt_filename: False
period_wandb_full_scale_im: 1
log_inputs_and_targets_to_wandb: True

# dataset parameters
data_root: './data/'
filetype: '.tif'
split_cfg: 'csv'
create_csv_w_split_cfg: True
path_train_split_csv: './runs/unet/sample/config/train.csv'
path_val_split_csv: './runs/unet/sample/config/train.csv' # Val on train to evaluate overfitting
path_test_split_csv: './runs/unet/sample/config/test.csv' 
path_eval_split_csv: './runs/unet/sample/config/eval.csv'
in_keys: ['pmw', 'mar_wa1']
in_keys_static: ['dem']
in_keys_aux: []
# Paths to data variables; relative to data_root
path_time_interpolate_sar: 'interim/runs/time_interpolate_mar/data_s1x/predictions/'
path_pmw: 'raw/Helheim_data/sample/PMW/'
path_modis_b1: 'raw/Helheim_data/sample/MODIS/MOD09GA_b01/'
path_modis_b2: 'raw/Helheim_data/sample/MODIS/MOD09GA_b02/'
path_mar_wa1: 'raw/Helheim_data/sample/MAR/MARv3.12/WA1/'
path_melt: 'raw/Helheim_data/sample/SAR/S1X/HH_PercentMelt/'
path_melt_reference: 'raw/Helheim_data/sample/SAR/S1X/HH_PercentMelt/2018_09_10.tif'
# Paths to static variables
path_landmask: 'raw/Helheim_data/sample/GIMP_Mask/landMask_100m.tif'
path_dem: 'raw/Helheim_data/sample/GrIMP_DEM/dem_100m.tif'
# The mean and std were calculated on the 370 imgs in the data_v1_4 train set 
mean_pmw: 206.1035919189453
mean_modis_b1: 0.6493049127465401
mean_modis_b2: 0.5751748354933877
mean_mar_wa1: 0.005986050236970186
mean_melt: 0.1931522637605667
mean_dem: 1175.09423828125
std_pmw: 26.77197265625
std_modis_b1: 0.3393826722741524
std_modis_b2: 0.30517456763241924
std_mar_wa1: 0.008952183648943901
std_melt: 0.3040434420108795
std_dem: 993.8522338867188
nodata_modis: -999
max_modis: 10000
max_mar_wa1: 1.
min_melt: 0.
max_melt: 1.

# Data transformation and augmentation parameters
use_batch_blur: False
pmw_GaussianBlur_kernel_size: 1.
pmw_GaussianBlur_sigma: 1.
mar_wa1_GaussianBlur_kernel_size: 1.
mar_wa1_GaussianBlur_sigma: 1.

dtype: 'float32'
amp: False
persistent_workers: True

# training hyperparameters
epochs: 5
batch_size: 2
img_size: [256,256]
val_percent: 0.34
test_percent: 0.34
optimizer: 'adam'
weight_decay: 0.001
loss_function: 'l1'

activation: 'gelu'
out_activation: null
num_extra_convs: 0
bilinear: False
out_channels: 1

# Step learning rate scheduler 
lr_scheduler: 'ReduceLROnPlateau'
lr_patience: 5

# CosineAnnealingWarmRestarts lerning rate scheduler config
# lr_scheduler: 'CosineAnnealingWarmRestarts'
use_cosine_annealing: True
T_0: 35
T_mult: 2
eta_min: 0.

# Logging a more stable evaluation metric to wandb this will evaluate on a static eval dataset and whole tiffs.
# we implemented this because the validation step while training will take random tiles from the val split.
# this will lead to a unstable validation metric.
periodical_evaluation: True
periodical_evaluation_include_ssim: True
epochs_between_periodical_evaluation: 10 # period in epochs between evalutions
epochs_between_checkpoint_save: 100 # period in epochs between saving checkpoints
starting_epoch: 1 # epochs before starting evaluation

### Learning rate
learning_rate: 0.001

# Evaluation parameters
prediction_batch_size: 8
prediction_stride: 192
# prediction_stride = img_size - 2*erode_size
# 256 - 2*32 = 192
erode_size: 32
apply_landmask_to_predictions: False